name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
                  
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_TOKEN }} 
          registry: ghcr.io  

    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Test/
          file: /Test/Dockerfile 
          push: true  
          tags: ghcr.io/javith-kapden/firewall-Test:latest
