name: Trivy Repository Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Trivy to scan the repository
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repository'
          format: 'table'
          ignore-unfixed: true
          exit-code: 1
